# Generated by Django 3.0.5 on 2021-12-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='documents_verified',
        ),
        migrations.AddField(
            model_name='profile',
            name='documents_verified',
            field=models.BooleanField(default=False),
        ),
    ]
