# Generated by Django 3.0.5 on 2021-12-11 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20211212_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transactions',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transactions',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'INITIATED'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], default='INITIATED', max_length=30),
        ),
        migrations.AddField(
            model_name='transactions',
            name='to_account_holder_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='to_account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='to_ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
