# Generated by Django 3.0.5 on 2021-12-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20211212_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
